### ISSUE TITLE
Trying to read an mp3 throws an exception

### ISSUE THREAD

**Issue by Gargamelism** [zsau/id3#1]
When I try to read an mp3, I get an
`IllegalArgumentException No method in multimethod 'body-codec' for dispatch value: null`

My code is 
`(id3/with-mp3 [mp3 "04. Stevie.mp3"]
              mp3)`

I know the path is correct because I can't rename the file afterwards unless I close the repl

**Comment by zsau** [comment]
Thanks for the report. Can you post the full stack trace and the mp3 file?

**Comment by Gargamelism** [comment]
I tried to reproduce now and it seems to work fine.
Thanks anyway
